export const theme = {
  colors: {
    deepGreen: '#006B3F',
    darkGreen: '#004D2C',
    orange: '#FF6B00',
    orangeSoft: '#FFF4E8',
    lightGreen: '#EAF7EF',
    background: '#F8FAF9',
    surface: '#FFFFFF',
    surfaceMuted: '#F1F5F3',
    white: '#FFFFFF',
    textDark: '#111827',
    textMuted: '#6B7280',
    border: '#E5E7EB',
    borderStrong: '#CBD5E1',
    error: '#DC2626',
    errorSoft: '#FEE2E2',
    success: '#16A34A',
    successSoft: '#DCFCE7',
    info: '#2563EB',
    infoSoft: '#DBEAFE',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
  },
  typography: {
    hero: {
      fontSize: 40,
      lineHeight: 46,
      fontWeight: '900',
    },
    title: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '900',
    },
    subtitle: {
      fontSize: 20,
      lineHeight: 28,
      fontWeight: '800',
    },
    body: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400',
    },
    bodyStrong: {
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '800',
    },
    caption: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '600',
    },
    label: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '800',
    },
  },
  layout: {
    screenPadding: 20,
    maxContentWidth: 720,
    controlHeight: 54,
    iconTile: 64,
  },
} as const;
