import type { Category, Product, Rider } from '../types/domain';

export const SERVICE_AREAS = [
  'Lumley',
  'Aberdeen',
  'Wilberforce',
  'Congo Cross',
  'Hill Station',
  'Kissy',
  'Juba',
  'Murray Town',
] as const;

export const MARKET_CATEGORIES: Category[] = [
  { id: 'vegetables', name: 'Vegetables', description: 'Fresh daily market vegetables.' },
  { id: 'fruits', name: 'Fruits', description: 'Seasonal fruit picks.' },
  { id: 'rice', name: 'Rice', description: 'Staple rice bags and household sizes.' },
  { id: 'meat', name: 'Meat', description: 'Market meat packs.' },
  { id: 'fish', name: 'Fish', description: 'Fresh fish and cold packs.' },
  { id: 'ingredients', name: 'Cooking Ingredients', description: 'Oil, spices, and pantry goods.' },
  { id: 'household', name: 'Household Items', description: 'Everyday home essentials.' },
  { id: 'beverages', name: 'Beverages', description: 'Soft drinks and refreshment packs.' },
];

export const MARKET_PRODUCTS: Product[] = [
  {
    id: 'fresh-tomatoes',
    categoryId: 'vegetables',
    name: 'Fresh Tomatoes',
    description: 'Basket of fresh market tomatoes.',
    price: 45,
    unit: 'basket',
    stockQuantity: 32,
    isAvailable: true,
  },
  {
    id: 'onions-red',
    categoryId: 'vegetables',
    name: 'Onions Red',
    description: 'Red onions sold per kilogram.',
    price: 25,
    unit: 'kg',
    stockQuantity: 50,
    isAvailable: true,
  },
  {
    id: 'cabbage',
    categoryId: 'vegetables',
    name: 'Cabbage',
    description: 'Fresh cabbage head.',
    price: 20,
    unit: 'head',
    stockQuantity: 28,
    isAvailable: true,
  },
  {
    id: 'rice-bag',
    categoryId: 'rice',
    name: 'Rice',
    description: 'Household rice bag.',
    price: 120,
    unit: 'bag',
    stockQuantity: 18,
    isAvailable: true,
  },
  {
    id: 'fish-pack',
    categoryId: 'fish',
    name: 'Fish',
    description: 'Fresh fish pack.',
    price: 80,
    unit: 'pack',
    stockQuantity: 14,
    isAvailable: true,
  },
  {
    id: 'meat-pack',
    categoryId: 'meat',
    name: 'Meat',
    description: 'Market meat pack.',
    price: 100,
    unit: 'pack',
    stockQuantity: 12,
    isAvailable: true,
  },
  {
    id: 'cooking-oil',
    categoryId: 'ingredients',
    name: 'Cooking Oil',
    description: 'Bottle of cooking oil.',
    price: 65,
    unit: 'bottle',
    stockQuantity: 24,
    isAvailable: true,
  },
  {
    id: 'soft-drinks',
    categoryId: 'beverages',
    name: 'Soft Drinks',
    description: 'Pack of soft drinks.',
    price: 30,
    unit: 'pack',
    stockQuantity: 36,
    isAvailable: true,
  },
];

export const DEMO_RIDERS: Rider[] = [
  { id: 'ibrahim-kamara', fullName: 'Ibrahim Kamara', phone: '+232 76 000 101', status: 'available' },
  { id: 'alpha-jalloh', fullName: 'Alpha Jalloh', phone: '+232 76 000 102', status: 'available' },
  { id: 'amadu-bah', fullName: 'Amadu Bah', phone: '+232 76 000 103', status: 'offline' },
  { id: 'mohamed-kanu', fullName: 'Mohamed Kanu', phone: '+232 76 000 104', status: 'busy' },
  { id: 'sulaiman-turay', fullName: 'Sulaiman Turay', phone: '+232 76 000 105', status: 'available' },
  { id: 'joseph-conteh', fullName: 'Joseph Conteh', phone: '+232 76 000 106', status: 'offline' },
];
